### ISSUE TITLE
Support pyspark

### ISSUE THREAD

**Issue by melin** [vesoft-inc/nebula-spark-connector#19]
Pyspark is best supported. Algorithmic people are familiar with Python and easy to use

**Comment by harryprince** [comment]
same need +1

**Comment by wey-gu** [comment]
@melin @harryprince 
I had spent some time today to figure out that pyspark is supported out of box, I will write more in doc/blog later.
```python
df = spark.read.format("com.vesoft.nebula.connector.NebulaDataSource").option("type", "vertex").option("spaceName", "basketballplayer").option("label", "player").option("returnCols", "name,age").option("metaAddress", "metad0:9559").option("partitionNumber", 1).load()

>>> df.show(n=2)
+---------+--------------+---+
|_vertexId|          name|age|
+---------+--------------+---+
|player105|   Danny Green| 31|
|player109|Tiago Splitter| 34|
+---------+--------------+---+
only showing top 2 rows
```

**Comment by wey-gu** [comment]
Article here: https://www.siwei.io/spark-on-nebula-graph/

**Comment by harryprince** [comment]
does the schema information could be detected automatically like we use Hive with meta info?
specific schema via option seems not a better way, when the column list is too long.

**Comment by wey-gu** [comment]
> ```python
> returnCols
> ```

I think you could use nebula-python client to fetch meta easier(it should be working to do so via spark-c, too with this py4j under the hood, i didn't try that yet), while, please be noted `returnCols` isn't mandatory, if it's omitted, all prop will be fetched by default.

**Comment by wey-gu** [comment]
Now both write and read examples were provided https://github.com/vesoft-inc/nebula-spark-connector/pull/55
