### ISSUE TITLE
Spark-Connector：Compatible with spark2.2

### ISSUE THREAD

**Issue by Nicole00** [vesoft-inc/nebula-spark-connector#2]
1. develop nebula-spark-connector with spark 2.2， which means use SparkSQL's DataSource v1 to extend Nebula datasource. 
2. nebula-spark-connector with spark 2.2 should be a dependent module in this repo.
3. make this product's name as neubla-spark-connector_2.2.

**Comment by handsonbao** [comment]
our partner pushi wants to transfer from Janus to Nebula. But they now use spark 2.2. It will be great if we can support as soon as possible.
