### ISSUE TITLE
add spark-connect  java api

### ISSUE THREAD

**Issue by qianjiangchao1992** [vesoft-inc/nebula-spark-connector#41]
现在工作大部分都用java来写的Spark ,希望能够提供java版本的api

**Comment by darionyaphet** [comment]
`Scala` 和 `Java`是可以互操作的  所以Java 也可以使用 Scala 的API

**Comment by qianjiangchao1992** [comment]
> `Scala` 和 `Java`是可以互操作的 所以Java 也可以使用 Scala 的API

我在IDEA引用scala  这个类NebulaDataFrameWriter  好像不太行   其他的可以引用

**Comment by wey-gu** [comment]
@qianjiangchao1992 不知道这会不会有帮助到你？

https://stackoverflow.com/questions/23261075/compiling-scala-before-alongside-java-with-gradle

**Comment by qianjiangchao1992** [comment]
> NebulaDataFrameWriter是一个隐式类
是这样的

**Comment by qianjiangchao1992** [comment]
> @qianjiangchao1992 不知道这会不会有帮助到你？
> 
> https://stackoverflow.com/questions/23261075/compiling-scala-before-alongside-java-with-gradle

我去试试  谢谢啊

**Comment by wey-gu** [comment]
> 

嗯嗯，抱歉~~

http://blog.muhuk.com/2016/05/24/how_to_call_scala_from_java__using_scala_classes.html

**Comment by Nicole00** [comment]
> > `Scala` 和 `Java`是可以互操作的 所以Java 也可以使用 Scala 的API
> 
> 我在IDEA引用scala 这个类NebulaDataFrameWriter 好像不太行 其他的可以引用

在java中这样调用scala的接口：
```
package$.MODULE$.NebulaDataFrameReader(spark.read()).nebula
package$.MODULE$.NebulaDataFrameWriter(df.write()).nebula
```
