### ISSUE TITLE
spark-connect 的jar包大小是100m,它太大了超过了我们平台的大小限制

### ISSUE THREAD

**Issue by PhilosophyBuns** [vesoft-inc/nebula-spark-connector#43]
为什么一个connect需要这么大的体积，这完全不符合常理

**Comment by randomJoe211** [comment]
@PhilosophyBuns Hi! The repo you submitted this issue was the doc repo. I transferred this issue to the nebula-spark-connector repo.

**Comment by PhilosophyBuns** [comment]
奇怪的是我在引用nebula-spark-connector后就会引入scala 即便我exclusion后scala也依然还在，这导致我打包和spark上存在的scala冲突

**Comment by Nicole00** [comment]
> 奇怪的是我在引用nebula-spark-connector后就会引入scala 即便我exclusion后scala也依然还在，这导致我打包和spark上存在的scala冲突

您项目中是否还引用的其他依赖scala包的依赖？ 我试了下exclusion掉scala-library包，dependencies中就不存在它了
```
<dependency>
            <groupId>com.vesoft</groupId>
            <artifactId>nebula-spark-connector</artifactId>
            <version>3.0.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>scala-library</artifactId>
                    <groupId>org.scala-lang</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```
![image](https://user-images.githubusercontent.com/16240361/201010853-989bc9f4-9112-4dcb-ba51-4abf611bc6c6.png)
