### ISSUE TITLE
能否提供3.0-snapshot版本的jar包，以及给予更加详细的使用教程，辛苦辛苦

### ISSUE THREAD

**Issue by liangye20** [vesoft-inc/nebula-spark-connector#50]

**Comment by wey-gu** [comment]
https://www.siwei.io/spark-on-nebula-graph/

这里有可以无障碍编译的容器环境，还一并提供了能跑通的 example jar 和一起连接的 nebula 集群环境。可以参考一下。

**Comment by Reid00** [comment]
@wey-gu  hi siwei 我在尝试用pyspark 的 spark-connector 写入数据，但是当我尝试连接读取数据的时候碰到了这个错误，能否帮忙排查下：
![image](https://user-images.githubusercontent.com/38450639/185284397-509c133f-1f3d-4731-bf6a-d113b904bdd9.png)

已知我目前做了这些：
1. 所在机器可以ping 通nebula 所在服务器
2. nebula-spark-connector-3.0.0.jar 放到了spark 2.4 的jar 文件夹下

请问这个如何排查这个问题？
BTW: https://www.siwei.io/spark-on-nebula-graph/  这个blog 写的挺好的，但是主要针对的是用docker 一键部署尝鲜的情况，
有没有完整的python sample 如何使用spark-connector 去读取，写入数据。

**Comment by wey-gu** [comment]
> @wey-gu  hi siwei 我在尝试用pyspark 的 spark-connector 写入数据，但是当我尝试连接读取数据的时候碰到了这个错误，能否帮忙排查下：
> 
> ![image](https://user-images.githubusercontent.com/38450639/185284397-509c133f-1f3d-4731-bf6a-d113b904bdd9.png)
> 
> 
> 
> 已知我目前做了这些：
> 
> 1. 所在机器可以ping 通nebula 所在服务器
> 
> 2. nebula-spark-connector-3.0.0.jar 放到了spark 2.4 的jar 文件夹下
> 
> 
> 
> 请问这个如何排查这个问题？
> 
> BTW: https://www.siwei.io/spark-on-nebula-graph/  这个blog 写的挺好的，但是主要针对的是用docker 一键部署尝鲜的情况，
> 
> 有没有完整的python sample 如何使用spark-connector 去读取，写入数据。

您的版本是匹配的么？报错像是指向了版本匹配。

另外 nebula-spark-c 的读走的是 storaged，所以网络上也有需求（https://www.siwei.io/nebula-algo-spark-k8s/ ）

**Comment by Reid00** [comment]
- spark version 2.4.0
- nebula-spark-connector-3.0.0.jar 用的是这个jar 包
- nebula 版本 v3.2.0
当我用python 代码直接连接，而不是用pyspark shell的使用，报错是这个
![image](https://user-images.githubusercontent.com/38450639/185327768-4a88adab-36f4-4aa6-94a0-481e67e0b57b.png)

**Comment by wey-gu** [comment]
> - spark version 2.4.0
> 
> - nebula-spark-connector-3.0.0.jar 用的是这个jar 包
> 
> - nebula 版本 v3.2.0
> 
> 当我用python 代码直接连接，而不是用pyspark shell的使用，报错是这个
> 
> ![image](https://user-images.githubusercontent.com/38450639/185327768-4a88adab-36f4-4aa6-94a0-481e67e0b57b.png)
> 
> 

/spark/bin/pyspark --driver-class-path nebula-spark-connector-3.0.0.jar --jars nebula-spark-connector-3.0.0.jar

class-path 是给了的对么？

**Comment by Reid00** [comment]
```
[root@qcc-hd-test-3 spark240]# ./bin/pyspark --driver-class-path ./jars/nebula-spark-connector-3.0.0.jar --jars ./jars/nebula-spark-connector-3.0.0.jar
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/opt/spark240/jars/nebula-spark-connector-3.0.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/spark240/jars/slf4j-log4j12-1.7.16.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/opt/cloudera/parcels/CDH-5.15.2-1.cdh5.15.2.p0.3/jars/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Setting default log level to "WARN".
```
这次添加了--driver-class-path nebula-spark-connector-3.0.0.jar --jars nebula-spark-connector-3.0.0.jar  再pyspark shell 中还是相同的错误
在python 代码中不知道怎么添加这个jar

**Comment by Nicole00** [comment]
> @wey-gu hi siwei 我在尝试用pyspark 的 spark-connector 写入数据，但是当我尝试连接读取数据的时候碰到了这个错误，能否帮忙排查下： ![image](https://user-images.githubusercontent.com/38450639/185284397-509c133f-1f3d-4731-bf6a-d113b904bdd9.png)
> 
> 已知我目前做了这些：
> 
> 1. 所在机器可以ping 通nebula 所在服务器
> 2. nebula-spark-connector-3.0.0.jar 放到了spark 2.4 的jar 文件夹下
> 
> 请问这个如何排查这个问题？ BTW: https://www.siwei.io/spark-on-nebula-graph/ 这个blog 写的挺好的，但是主要针对的是用docker 一键部署尝鲜的情况， 有没有完整的python sample 如何使用spark-connector 去读取，写入数据。

你可以看下报错日志，你用的nebula一定是2.6.x版本的，不是3.2.0。 客户端版本和服务端不兼容

**Comment by Reid00** [comment]
```sh
py4j.protocol.Py4JJavaError: An error occurred while calling o98.load.
: com.facebook.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
        at com.facebook.thrift.transport.TSocket.open(TSocket.java:206)
        at com.vesoft.nebula.client.meta.MetaClient.getClient(MetaClient.java:148)
        at com.vesoft.nebula.client.meta.MetaClient.doConnect(MetaClient.java:127)
        at com.vesoft.nebula.client.meta.MetaClient.connect(MetaClient.java:116)
        at com.vesoft.nebula.connector.nebula.MetaProvider.<init>(MetaProvider.scala:53)
        at com.vesoft.nebula.connector.reader.NebulaSourceReader.getSchema(NebulaSourceReader.scala:44)
        at com.vesoft.nebula.connector.reader.NebulaSourceReader.readSchema(NebulaSourceReader.scala:30)
        at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:175)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:204)
        at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:167)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
        at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
        at py4j.Gateway.invoke(Gateway.java:282)
        at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
        at py4j.commands.CallCommand.execute(CallCommand.java:79)
        at py4j.GatewayConnection.run(GatewayConnection.java:238)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at com.facebook.thrift.transport.TSocket.open(TSocket.java:201)
        ... 20 more
```
是的，刚刚ip 错了，换了3.2.0 的nebula ip 出现了refused

```sh
[root@qcc-hd-test-3 spark240]# ping 10.0.7.142
PING 10.0.7.142 (10.0.7.142) 56(84) bytes of data.
64 bytes from 10.0.7.142: icmp_seq=1 ttl=53 time=7.69 ms
64 bytes from 10.0.7.142: icmp_seq=2 ttl=53 time=7.58 ms
^C
--- 10.0.7.142 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 7.580/7.637/7.694/0.057 ms
```
ping 了之后发现是可以。 是因为没有指定账号密码吗？

**Comment by Reid00** [comment]
刚刚因为IP 写错的原因，测试了下，在shell 可以正常运行了.
但是在python 文件中如何写代码？下面的写法本地调试不通
```python
if __name__ == "__main__":
    spark = SparkSession.builder.appName("nebula-connector").getOrCreate()

    df = spark.read.format(
        "com.vesoft.nebula.connector.NebulaDataSource").option(
        "type", "vertex").option(
        "spaceName", "Relation").option(
        "label", "Company").option(
        "returnCols", "keyno,name").option(
        "metaAddress", "10.0.7.00:9559").option(
        "partitionNumber", 1).load()

    df.show(7, truncate=False)
```

**Comment by Reid00** [comment]
need to add specific jars in sparkSession
```python
if __name__ == "__main__":

    spark = SparkSession.builder\
            .config("spark.jars", "/opt/spark240/jars/nebula-spark-connector-3.0.0.jar")\
            .appName("nebula-connector").getOrCreate()

    df = spark.read.format(
        "com.vesoft.nebula.connector.NebulaDataSource").option(
        "type", "vertex").option(
        "spaceName", "Relation").option(
        "label", "Company").option(
        "returnCols", "keyno,name").option(
        "metaAddress", "10.0.7.89:9559").option(
        "partitionNumber", 1).load()

    df.show(7, truncate=False)

```

**Comment by Reid00** [comment]
又有另外一个问题，scala 中写入数据Nebula config 是这样写的
https://github.com/vesoft-inc/nebula-spark-connector/blob/6b80a2ff9d481abb89307f8f18ca5580256d5f2d/example/src/main/scala/com/vesoft/nebula/examples/connector/NebulaSparkWriterExample.scala#L52

python 中怎么写入这个connector config 吗？ 还是python 版本无法写？

```python
import com.vesoft.nebula.connector.{
  NebulaConnectionConfig,
  WriteMode,
  WriteNebulaEdgeConfig,
  WriteNebulaVertexConfig
}
```

**Comment by wey-gu** [comment]
> 又有另外一个问题，scala 中写入数据Nebula config 是这样写的
> 
> https://github.com/vesoft-inc/nebula-spark-connector/blob/6b80a2ff9d481abb89307f8f18ca5580256d5f2d/example/src/main/scala/com/vesoft/nebula/examples/connector/NebulaSparkWriterExample.scala#L52
> 
> 
> 
> python 中怎么写入这个connector config 吗？ 还是python 版本无法写？
> 
> 
> 
> ```python
> 
> import com.vesoft.nebula.connector.{
> 
>   NebulaConnectionConfig,
> 
>   WriteMode,
> 
>   WriteNebulaEdgeConfig,
> 
>   WriteNebulaVertexConfig
> 
> }
> 
> ```
> 
> 

👍 哈你找到了在非 pyshell 里加载 jar 给 spark session 的方式。

我之前是“零知识”研究的弄通读的，写还没弄过，不过我在这篇文章的英文版里放了我是怎么找到call reader 的方式并 map 对应读的配置的 string 的，你可以把那个 blog 的语言切换英文看一下。

手机回复不方便弄，我这几天在出差路上🤦‍♂️。

如果不行，我回头找时间研究一下哈。

**Comment by Nicole00** [comment]
> python 中怎么写入这个connector config 吗？ 还是python 版本无法写？

pyspark的写法参考siwei的这个readme说明：https://github.com/wey-gu/nebula-up， 他这个repo很棒，有使用示例的

**Comment by Reid00** [comment]
@Nicole00  多谢回复。我刚刚把这个repo 看了下，没找到 如何在Python 文件中调用jar 包里面的com.vesoft.nebula.connector. 中的NebulaConnectionConfig, 方法 😥

**Comment by wey-gu** [comment]
在 @Nicole00 的帮助下，例子可以跑通了，参考

https://github.com/vesoft-inc/nebula-spark-connector/pull/55

**Comment by Nicole00** [comment]
@Reid00 Hi，你的问题解决了没，该issue 要被close了

**Comment by Reid00** [comment]
yes, thank you for your help @wey-gu  @Nicole00  😀
