### ISSUE TITLE
求解，pyspark 通过nebula-spark-connector写入边，边属性怎么写进去？

### ISSUE THREAD

**Issue by jindyliu** [vesoft-inc/nebula-spark-connector#64]

**Comment by Nicole00** [comment]
参考readme 中wey-gu 加的的pyspark使用示例哈，https://github.com/vesoft-inc/nebula-spark-connector#pyspark-with-nebula-spark-connector

写边的时候，你的dataframe里面所有除了配置成src id、dst id 和 rank的字段以外的其他列 都会作为属性写入NebulaGraph。所以你要在调用df.write.format 之前 可以对你的dataframe做一下列裁剪和rename，使dataframe schema中的字段名和NebulaGraph中的属性名保持一致。

**Comment by QingZ11** [comment]
@jindyliu 这个问题解决了么？如果解决了的话，可以关闭下 issue 哈。
