### ISSUE TITLE
[feat] Intergrate with Alibaba/GraphAr

### ISSUE THREAD

**Issue by whitewum** [vesoft-inc/nebula-spark-connector#76]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Ref to [GraphAr](https://github.com/alibaba/GraphAr)  and [this planing feature](https://github.com/alibaba/GraphAr/issues/34)

**Comment by liuxiaocs7** [comment]
Hi, @wey-gu, i want to try this task in HACKTOBERFEST, please assign to me~
BTW, the pr should in https://github.com/alibaba/GraphAr repository?

**Comment by wey-gu** [comment]
Yes, exactly, this is actually a very old task, I didn't expect you would like to hack on that 👍!

If needed we could break down into multiple subtasks that's marked with hacktoberfest, dont forget to register BTW, referring to https://bit.ly/hack-nebula

**Comment by wey-gu** [comment]
ping @Nicole00

**Comment by liuxiaocs7** [comment]
Hi, @wey-gu, PR created: https://github.com/alibaba/GraphAr/pull/244, PTAL when free, thanks!~

**Comment by wey-gu** [comment]
Amazing work @liuxiaocs7 hopefully we can get it reviewed and merged in October!

**Comment by wey-gu** [comment]
PR merged via https://github.com/alibaba/GraphAr/pull/244 🎉

add hacktoberfest-accepted here, too

THANKS @liuxiaocs7 !!!
