### ISSUE TITLE
nebula spark connector and spark versions compatibility

### ISSUE THREAD

**Issue by manyfeatures** [vesoft-inc/nebula-spark-connector#82]
Hi!
Are all releases of Nebula spark connector only compatible with spark 2.2/2.4?

**Comment by wey-gu** [comment]
Dear @manyfeatures ,

That's true as of now the https://github.com/vesoft-inc/nebula-spark-connector/pull/71 is not being merged(and not included in a release).

@Nicole00 do we have any rough plan on when it'll be merged? I guess it could be included in the 3.4.0 release cycle, right?

**Comment by Nicole00** [comment]
> Dear @manyfeatures ,
> 
> That's true as of now the #71 is not being merged(and not included in a release).
> 
> @Nicole00 do we have any rough plan on when it'll be merged? I guess it could be included in the 3.4.0 release cycle, right?

not in the plan. I'll merge it soon

**Comment by wey-gu** [comment]
Spark connector now supports spark 3.0 :) with https://github.com/vesoft-inc/nebula-spark-connector/pull/71 by @Nicole00 !
